import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
{/* 
<head>
            <meta charSet="utf-8" />
            <title>Conduit</title>
            {/ Import Ionicon icons & Google Fonts our Bootstrap theme relies on /}
            <link
                href="//code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css"
                rel="stylesheet"
                type="text/css"
            />
            <link
                href="//fonts.googleapis.com/css?family=Titillium+Web:700|Source+Serif+Pro:400,700|Merriweather+Sans:400,700|Source+Sans+Pro:400,300,600,700,300italic,400italic,600italic,700italic"
                rel="stylesheet"
                type="text/css"
            />
            {/ Import the custom Bootstrap 4 theme from our hosted CDN /}
            <link rel="stylesheet" href="//demo.productionready.io/main.css" />
        </head>
        <body>
          <Header />
          <p>This is the main page</p>
          <Footer />
        </body>*/}